version: '3'
services:
  selenium-hub:
    image: selenium/hub:4.0.0-alpha-7-prerelease-20200921
    ports:
      - "5442:4442"
      - "5443:4443"
      - "5444:4444"
  chrome:
    image: selenium/node-chrome:4.0.0-alpha-7-prerelease-20200921
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "7900:5900"